/* AUTO-GENERATED by api/api-generator/generate.mjs. Do not edit manually. */
export const GENERATED_API_VERSION = "1.0.0" as const;
export const GENERATED_PUBLIC_API_URL = "https://api.capilot.powerchain.energy/v1" as const;
export const GENERATED_APP_GATEWAY_URL = "https://capilot.powerchain.app/v1" as const;
export const GENERATED_API_OPERATIONS = [
  {
    "operationId": "connectChatWebSocket",
    "method": "GET",
    "path": "/ws/v1/chat/{id}"
  },
  {
    "operationId": "createChat",
    "method": "POST",
    "path": "/v1/chat"
  },
  {
    "operationId": "createContactRequest",
    "method": "POST",
    "path": "/v1/contact"
  },
  {
    "operationId": "generateAnalysis",
    "method": "POST",
    "path": "/v1/ai/generate"
  },
  {
    "operationId": "getChat",
    "method": "GET",
    "path": "/v1/chat/{id}"
  },
  {
    "operationId": "getCredits",
    "method": "GET",
    "path": "/v1/credits"
  },
  {
    "operationId": "getCurrentSession",
    "method": "GET",
    "path": "/v1/sessions/current"
  },
  {
    "operationId": "getDashboard",
    "method": "GET",
    "path": "/v1/dashboard"
  },
  {
    "operationId": "getDefaultCopilotMessages",
    "method": "GET",
    "path": "/v1/copilot"
  },
  {
    "operationId": "getHealth",
    "method": "GET",
    "path": "/v1/health"
  },
  {
    "operationId": "getMarketPrice",
    "method": "GET",
    "path": "/v1/market/price"
  },
  {
    "operationId": "getMessage",
    "method": "GET",
    "path": "/v1/messages/{id}"
  },
  {
    "operationId": "getNetworkProfile",
    "method": "GET",
    "path": "/v1/network/profile"
  },
  {
    "operationId": "getPwrcToken",
    "method": "GET",
    "path": "/v1/tokens/pwrc"
  },
  {
    "operationId": "getSessionSecurity",
    "method": "GET",
    "path": "/v1/security/session"
  },
  {
    "operationId": "getSolanaHealth",
    "method": "GET",
    "path": "/v1/network/solana"
  },
  {
    "operationId": "listAiModels",
    "method": "GET",
    "path": "/v1/ai/models"
  },
  {
    "operationId": "listApprovals",
    "method": "GET",
    "path": "/v1/approvals"
  },
  {
    "operationId": "listAssets",
    "method": "GET",
    "path": "/v1/assets"
  },
  {
    "operationId": "listChats",
    "method": "GET",
    "path": "/v1/chat"
  },
  {
    "operationId": "listCreditLedger",
    "method": "GET",
    "path": "/v1/credits/ledger"
  },
  {
    "operationId": "listCreditQuotes",
    "method": "GET",
    "path": "/v1/credits/quotes"
  },
  {
    "operationId": "listCreditReceipts",
    "method": "GET",
    "path": "/v1/credits/receipts"
  },
  {
    "operationId": "listServices",
    "method": "GET",
    "path": "/v1/services"
  },
  {
    "operationId": "listSessions",
    "method": "GET",
    "path": "/v1/sessions"
  },
  {
    "operationId": "listTokens",
    "method": "GET",
    "path": "/v1/tokens"
  },
  {
    "operationId": "openDemoWorkspace",
    "method": "POST",
    "path": "/v1/auth/demo"
  },
  {
    "operationId": "registerAccount",
    "method": "POST",
    "path": "/v1/auth/register"
  },
  {
    "operationId": "revokeSession",
    "method": "DELETE",
    "path": "/v1/sessions/{id}"
  },
  {
    "operationId": "sendChatMessage",
    "method": "POST",
    "path": "/v1/chat/{id}/messages"
  },
  {
    "operationId": "sendDefaultCopilotMessage",
    "method": "POST",
    "path": "/v1/copilot"
  },
  {
    "operationId": "signIn",
    "method": "POST",
    "path": "/v1/auth/sign-in"
  },
  {
    "operationId": "signOut",
    "method": "POST",
    "path": "/v1/auth/sign-out"
  },
  {
    "operationId": "updateApproval",
    "method": "POST",
    "path": "/v1/approvals/{id}"
  },
  {
    "operationId": "updateProfile",
    "method": "PATCH",
    "path": "/v1/profile"
  }
] as const;
export type GeneratedApiOperation = (typeof GENERATED_API_OPERATIONS)[number];
