import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const config = JSON.parse(await readFile(path.join(root, "api/api-generator/config.json"), "utf8"));
const spec = JSON.parse(await readFile(path.join(root, config.source), "utf8"));
const methods = new Set(["get","post","put","patch","delete","options","head"]);
const operations = [];
for (const [route, pathItem] of Object.entries(spec.paths ?? {})) {
  if (!pathItem || typeof pathItem !== "object") continue;
  for (const [method, operation] of Object.entries(pathItem)) {
    if (!methods.has(method) || !operation || typeof operation !== "object") continue;
    const operationId = typeof operation.operationId === "string" ? operation.operationId : `${method}_${route.replace(/[^a-z0-9]+/gi,"_")}`;
    operations.push({ operationId, method: method.toUpperCase(), path: route });
  }
}
operations.sort((a,b)=>a.operationId.localeCompare(b.operationId));
const output = `/* AUTO-GENERATED by api/api-generator/generate.mjs. Do not edit manually. */
export const GENERATED_API_VERSION = ${JSON.stringify(spec.info?.version ?? "unknown")} as const;
export const GENERATED_PUBLIC_API_URL = ${JSON.stringify(config.publicBaseUrl)} as const;
export const GENERATED_APP_GATEWAY_URL = ${JSON.stringify(config.appGatewayBaseUrl)} as const;
export const GENERATED_API_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;
export type GeneratedApiOperation = (typeof GENERATED_API_OPERATIONS)[number];
`;
const outputPath = path.join(root, config.output);
await mkdir(path.dirname(outputPath), { recursive: true });
if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) { console.error("Generated API catalog is stale. Run pnpm api:generate."); process.exit(1); }
  console.log(`API generator check passed (${operations.length} operations).`);
} else {
  await writeFile(outputPath, output);
  console.log(`Generated ${config.output} with ${operations.length} operations.`);
}
